config/routes.rb
Rails.application.routes.draw do
  root 'sessions#home'

  post '/payments' => 'payments#create'
  post '/pools' => 'pools#create'

  resource :sessions
  resource :users
  resource :addresses
  resource :external_accounts

  resource :stripe_accounts
  post '/tos' => 'stripe_accounts#tos', as: 'tos'


  resources :videos, except: [:show, :index]
  resources :projects, shallow: true do
    resources :categories_projects
    resources :images
    resources :logs
    resources :contents
    resources :categories
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :stripe_account

  validates :city, :state, :line1, :postal_code, presence: :true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categories_projects
  has_many :projects, through: :categories_projects
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :project
  validates :body, presence: true
end

app/models/external_account.rb
class ExternalAccount < ApplicationRecord
  belongs_to :stripe_account
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :project
  has_attached_file :pic, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/galaxy.jpg'
  validates_attachment_content_type :pic, content_type: /\Aimage\/.*\z/
end

app/models/log.rb
class Log < ApplicationRecord
  belongs_to :user
  belongs_to :project
  validates :title, :body, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :user
  belongs_to :pool

end

app/models/pool.rb
class Pool < ApplicationRecord
  belongs_to :project
  has_many :payments
  validates :goal, presence: true

  def progress
    pledged.to_f / goal * 100
  end

  def visual_progress
    progress <= 100 ? progress : 100
  end

  def backers
    payments.map { |pay| pay.user.username }.uniq.length
  end

  def creator
    project.user
  end

  def days_left
    ((deadline - Time.now) / 1.day).round
  end

  def add_payment(payment)
    total = payment.amount + pledged
    update(pledged: total)
  end

  def failure?
    return true if deadline - Time.now <= 0 && progress < 100
    false
  end

  def success?
    return false if failure?
    return true if progress > 100
    false
  end

  def still_in_progress?
    return false if failure || success
    true
  end

end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :user
  has_one :pool
  has_many :logs, dependent: :destroy
  has_many :images, dependent: :destroy
  has_one :video, dependent: :destroy
  has_many :contents, dependent: :destroy

  has_many :categories_projects
  has_many :categories, through: :categories_projects

  validates :title, presence: true, uniqueness: true

  scope :posted?, -> { where(posted: true) }

  def self.search(term)
    where(['title LIKE ?', "%#{term}%"])
  end

  def postable?
    pool && video && categories.length >= 1 && contents.length >= 4 && user.stripe_account ? true : false
  end

  def has_two_categories?
    categories.length >= 2 ? true : false
  end

end

app/models/stripe_account.rb
class StripeAccount < ApplicationRecord
  belongs_to :user
  has_one :address
  has_many :external_accounts

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :last_4_social, presence: true
  validates :date_of_birth, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :projects, dependent: :destroy
  has_many :payments
  has_many :logs
  has_one :stripe_account
  validates :username, presence: true
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :project
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :update, :destroy]

  def index
    @projects = Project.posted?.order('created_at DESC')
    @projects = @projects.search(params[:search]) if params[:search]
    @category = Category.find(params[:cat_id]) if params[:cat_id]
    @projects = @category.projects if params[:cat_id]
  end

  def show
    @category_project = @project.categories_projects.new
    @video = @project.video ? @project.video : Video.new
    @content = @project.contents.new
    @image = @project.images.new
    @log = @project.logs.new
    @payment = Payment.new
    @pool = Pool.new
  end

  def create
    @project = current_user.projects.new(project_params)
    return refresh_page unless @project.save
    redirect_to @project, notice: 'project successfully created'
  end

  def update
    return refresh_page unless @project.update(project_params)
    redirect_to @project, notice: 'project successfully updated'
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'project successfully destroyed'
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :posted)
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/logs_helper.rb
module LogsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/pools_helper.rb
module PoolsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/projects/_form.html.erb
<div class="reveal" id="crud-project" data-reveal>

    <%= form_for project do |f| %>

    <% if project.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(project.errors.count, "error") %>
            prohibited this project from being saved:</h2>

        <ul>
            <% project.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
    </div>
    <% end %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <% if project.postable? %>
    <%= f.label :posted %>
    <%= f.text_field :posted %>
    <% else %>
    <%= f.hidden_field :posted, value: false %>
    <% end %>
    <%= f.submit crud, class: "expanded large button" %>
    <% end %>
    <%= render 'projects/need-to-post' unless project.postable? || crud == 'Create project' %>
</div>

<% if crud == 'Create project' %>
<a data-open="crud-project" class="button expanded">Start a new project</a>
<% elsif crud == 'Edit project' %>
<a data-open="crud-project" class="button">Edit project</a>
<% end %>

app/views/projects/_info.html.erb
<div id="title" class="row align-center">
    <h2>
        <%= @project.title %>
    </h2>
</div>

<div class="row align-center">
    <%= youtube_frame @project.video.youtube_link if @project.video %>
</div>

<div id="title" class="row align-center">
    <h4>
        <strong>User:</strong>
        <%= @project.user.username %>
    </h4>
</div>

<div class="row align-center">
    <%= render 'categories/labels', project: @project %>
</div>

app/views/projects/_ledger.html.erb
<table class="hover small-4">
    <thead>
        <tr>
            <th>User</th>
            <th>Amount</th>
        </tr>
    </thead>
    <tbody>
        <% payments.each do |payment| %>
        <tr>
            <td><%= payment.user.username %></td>
            <td><%= payment.amount %></td>
        </tr>
        <% end %>
    </tbody>
</table>

app/views/projects/_need-to-post.html.erb
<div class="column">
  <h3>Fill these out to post</h3>
  <%= "video" unless @project.video %> <br>
  <%= "about" unless @project.contents.find_by(kind: 'about') %><br>
  <%= "context" unless @project.contents.find_by(kind: 'context') %><br>
  <%= "importance" unless @project.contents.find_by(kind: 'importance') %><br>
  <%= "goals" unless @project.contents.find_by(kind: 'goals') %><br>
  <%= "pool" unless @project.pool %><br>
  <%= "category" unless @project.categories.length > 0 %><br>
  <%= "stripe account" unless @project.user.stripe_account %>
</div>

app/views/projects/_search.html.erb
<%= form_tag(projects_path, :method => "get", id: "search-form", class: "medium-12") do %>
<div class="input-group">
    <span class="input-group-label">Explore</span>
    <%= text_field_tag :search, params[:search], placeholder: "Search for projects", class: "input-group-field" %>
    <div class="input-group-button">
        <%= submit_tag "Search", :name => nil, class: "button expanded" %>
    </div>
</div>
<% end %>

app/views/projects/_thumbs.html.erb
<div class="column">
    <% projects.each_slice(3) do |project| %>

    <div class="row align-spaced">

        <% project.each do |pro| %>

        <section class="column small-3" id=<%= pro.id.to_s %>>

            <div class="row">
                <%= image_tag 'galaxy.jpg' %>
            </div>

            <div class="callout row">
                <h3>
                    <%= pro.title %>
                </h3>
                <% if pro.categories.length > 0 %>
                <div class="row align-center">
                    <%= render "categories/labels", project: pro %>
                </div>
                <% end %>
                <div>

                    <%= render 'pools/thumb', pool: pro.pool %>
                </div>
            </div>

        </section>
        <% end %>

    </div>
    <% end %>

</div>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<%= render 'categories/list' %>

<%= render 'thumbs', projects: @projects %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<ul class="tabs" data-tabs id="example-tabs">
    <li class="tabs-title is-active">
        <a href="#panel1" aria-selected="true">Info</a>
    </li>
    <li class="tabs-title">
        <a href="#panel2">Comments</a>
    </li>
    <li class="tabs-title">
        <a href="#panel3">Fund</a>
    </li>
    <li class="tabs-title">
        <a href="#panel4">Payments</a>
    </li>
    <li class="tabs-title">
        <a href="#panel5">Images</a>
    </li>
</ul>

<div class="tabs-content" data-tabs-content="example-tabs">
    <div class="tabs-panel is-active" id="panel1">
        <div class="align-center column">
            <%= render 'info' %>
            <%= render 'categories/form', category_project: @category_project, project: @project unless @project.has_two_categories? %>
            <%= render 'form', project: @project, crud: 'Edit project' if users_project? %>
            <%= render 'videos/form', video: @video, project: @project if users_project? %>
            <div class="row align-center content-box"><%= render 'contents/project-content', content: @content, project: @project %></div>
        </div>
    </div>
    <div class="tabs-panel" id="panel2">
        <div class="medium-6" , id="log-list">
            <%= render 'logs/form', log: @log, project: @project if current_user %>
            <%= render 'logs/list', logs: @project.logs.order('created_at DESC') %>
        </div>
    </div>
    <div class="tabs-panel" id="panel3">
        <% if @project.pool %>
        <%= render 'pools/info', pool: @project.pool %>
        <%= render 'payments/checkout', payment: @payment, pool: @project.pool %>
        <% elsif users_project? %>
        <%= render 'pools/form', pool: @pool, project: @project.id %>
        <% end %>
    </div>
    <div class="tabs-panel" id="panel4">
        <%= render 'ledger', payments: @project.pool.payments if @project.pool %>
    </div>
    <div class="tabs-panel" id="panel5">
        <%= render 'images/form', image: @image, project: @project if users_project? %>
        <%= render 'images/list', images: @project.images %>
    </div>
</div>